"""
Speaker label preprocessing for corpus-specific formatting.

Strips speaker labels from CHILDES and Switchboard data before spaCy processing.
Returns (cleaned_text, metadata_dict) per line.

The CHILDES cleaner optionally loads age metadata from a sidecar JSON file
generated by scripts/generate_childes_metadata.py. When loaded, each utterance's
metadata dict includes child_age_months, child_age_source, childes_child,
and childes_corpus fields.
"""

import json
import re
from pathlib import Path
from typing import Dict, Optional, Tuple

from .constants import CHILDES_ADULT_SPEAKERS, CHILDES_CHILD_SPEAKERS

# Patterns
_CHILDES_PATTERN = re.compile(r"^\*([A-Z]{2,4}):\t(.*)$")
_SWITCHBOARD_PATTERN = re.compile(r"^([AB]):\t(.*)$")
_BOUNDARY_PATTERN = re.compile(r"^= = = childes/(.+)\.cha = = =$")
_IT_CORPUS_BOUNDARY = re.compile(r"^= = = = (.+) = = = =$")
_IT_FILE_BOUNDARY = re.compile(r"^= = = (.+)\.cha = = =$")
_BRACKET_TAG = re.compile(r"\[.*?\]")


class CHILDESCleaner:
    """
    Stateful CHILDES line cleaner that tracks file boundaries and age metadata.

    Detects file boundary markers (``= = = childes/... = = =``), strips
    bracket annotations (``[...]``), and returns child age in the metadata
    dict when a sidecar metadata file is loaded.
    """

    def __init__(self, metadata_path: Optional[Path] = None):
        self._age_index: Dict[str, dict] = {}
        self._current_age: Optional[int] = None
        self._current_age_source: Optional[str] = None
        self._current_child: Optional[str] = None
        self._current_corpus: Optional[str] = None

        if metadata_path and Path(metadata_path).exists():
            with open(metadata_path, "r") as f:
                self._age_index = json.load(f)

    def __call__(self, line: str) -> Tuple[str, Dict[str, Optional[str]]]:
        """
        Clean a single CHILDES line.

        Returns (cleaned_text, metadata). Returns empty string for
        boundary markers and annotation-only lines.
        """
        line = line.strip()

        # English file boundary marker — update age state, skip line
        bm = _BOUNDARY_PATTERN.match(line)
        if bm:
            path = bm.group(1)
            info = self._age_index.get(path, {})
            self._current_age = info.get("age_months")
            self._current_age_source = info.get("age_source")
            self._current_child = info.get("child")
            self._current_corpus = info.get("corpus")
            return "", {}

        # Italian corpus boundary (= = = = CorpusName = = = =) — update corpus, skip
        it_corpus = _IT_CORPUS_BOUNDARY.match(line)
        if it_corpus:
            self._current_corpus = it_corpus.group(1).strip()
            return "", {}

        # Italian file boundary (= = = 030409.cha = = =) — extract age + child, skip
        it_file = _IT_FILE_BOUNDARY.match(line)
        if it_file:
            filename = it_file.group(1).strip()
            child_name, age_months = self._parse_italian_file_boundary(filename)
            self._current_age = age_months
            self._current_age_source = "filename"
            self._current_child = child_name
            return "", {}

        # Annotation-only lines (start with [ but no speaker label)
        if line.startswith("["):
            return "", {}

        # Speaker-labeled utterance
        m = _CHILDES_PATTERN.match(line)
        if m:
            speaker_code = m.group(1)
            text = m.group(2).strip()

            # Strip bracket annotations from utterance text
            text = _BRACKET_TAG.sub("", text).strip()
            # Collapse multiple spaces left by bracket removal
            text = re.sub(r"  +", " ", text)

            if not text:
                return "", {}

            if speaker_code in CHILDES_CHILD_SPEAKERS:
                role = "child"
            elif speaker_code in CHILDES_ADULT_SPEAKERS:
                role = "adult"
            else:
                role = "unknown"

            meta = {
                "speaker": speaker_code,
                "role": role,
                "child_age_months": self._current_age,
                "child_age_source": self._current_age_source,
                "childes_child": self._current_child,
                "childes_corpus": self._current_corpus,
            }
            return text, meta

        # No match — return as-is (shouldn't happen in well-formed CHILDES)
        return line, {"speaker": None, "role": None}

    def _parse_italian_file_boundary(
        self, filename: str
    ) -> Tuple[Optional[str], Optional[int]]:
        """
        Extract child name and age from Italian CHILDES file boundary.

        Handles several formats found across Italian CHILDES corpora:
        - ``030409`` — age-only (YYMMDD), child from corpus name
        - ``Diana/011007`` — child/YYMMDD (Calambrone, Tonelli)
        - ``davide_18_233`` — child_agemonths_id (D'Odorico)

        Returns:
            (child_name, age_months) — either may be None.
        """
        # Format: Child/YYMMDD (Calambrone, Tonelli)
        if "/" in filename:
            parts = filename.split("/", 1)
            child = parts[0].strip()
            age = self._parse_yymmdd(parts[1].strip())
            return child, age

        # Format: childname_agemonths_id (D'Odorico)
        m = re.match(r"^([a-zA-Z]+)_(\d+)_\d+$", filename)
        if m:
            child = m.group(1).strip()
            age = int(m.group(2))
            return child, age

        # Format: YYMMDD only (Antelmi, Roma) — use corpus name as child proxy
        age = self._parse_yymmdd(filename)
        if age is not None:
            return self._current_corpus, age

        return None, None

    @staticmethod
    def _parse_yymmdd(name: str) -> Optional[int]:
        """Parse YYMMDD string (with optional letter suffix) to age in months.

        Returns None if the parsed age exceeds 120 months (10 years),
        which indicates a data entry error in the filename.
        """
        m = re.match(r"^(\d{2})(\d{2})(\d{2})[a-z]?$", name)
        if m:
            years = int(m.group(1))
            months = int(m.group(2))
            age = years * 12 + months
            if age > 120:
                return None
            return age
        return None


def clean_switchboard_line(line: str) -> Tuple[str, Dict[str, Optional[str]]]:
    """
    Strip Switchboard speaker labels.

    Input format: ``A:\\t utterance`` or ``B:\\t utterance``
    """
    m = _SWITCHBOARD_PATTERN.match(line)
    if m:
        speaker_label = m.group(1)
        text = m.group(2).strip()
        return text, {"speaker": speaker_label, "role": None}
    return line.strip(), {"speaker": None, "role": None}


def clean_generic_line(line: str) -> Tuple[str, Dict[str, Optional[str]]]:
    """Pass-through cleaner for corpora without speaker labels."""
    return line.strip(), {"speaker": None, "role": None}


def get_cleaner(genre: str, metadata_dir: Optional[Path] = None):
    """
    Return the appropriate line cleaner function for a genre.

    Args:
        genre: Genre name (e.g., "CHILDES", "Switchboard")
        metadata_dir: Directory containing childes_metadata.json.
            If None, CHILDES cleaner runs without age metadata.
    """
    genre_lower = genre.lower()
    if genre_lower == "childes":
        metadata_path = None
        if metadata_dir:
            candidate = Path(metadata_dir) / "childes_metadata.json"
            if candidate.exists():
                metadata_path = candidate
        return CHILDESCleaner(metadata_path=metadata_path)
    elif genre_lower == "switchboard":
        return clean_switchboard_line
    else:
        return clean_generic_line
