apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: corpus-analysis-data
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
