input_path: /mnt/data/italian/test_10M/
output_path: /mnt/data/output/it_test_10M/
split_name: it_test_10M
spacy_model: it_core_news_lg
spacy_batch_size: 256
spacy_disable_components:
  - ner
chunk_size: 5000
language: it
checkpoint_dir: /mnt/data/checkpoints/it_test_10M/
checkpoint_interval: 10000
genre_map:
  childes: CHILDES
  clta: CltA
  corpus_isacco: ISACCO
  europarl: Europarl
  leipzig_web: Leipzig Web
  paccss: PaCCSS
  qcri: QCRI
  spgc: SPGC
