input_path: data/italian_test/
output_path: data/output/it_local_test/
split_name: it_local_test
spacy_model: it_core_news_lg
spacy_batch_size: 64
spacy_disable_components:
  - ner
chunk_size: 500
language: it
annotation_mode: true
layered_output: true
annotators:
  - clause_structure
  - that_trace
  - expletive
  - pronoun
  - negation
  - wh_extraction
  - relative_clause
  - verb
  - argument_structure
  - topic
  - complexity
genre_map:
  europarl: Europarl
  leipzig_web: Leipzig Web
  paccss: PaCCSS
  qcri: QCRI
  spgc: SPGC
